"""nivayu

Revision ID: 708b19b898ac
Revises: 
Create Date: 2024-06-03 19:21:56.246253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '708b19b898ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='genderenum'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('married', sa.Enum('MARRIED', 'UNMARRIED', name='marriedenum'), nullable=False),
    sa.Column('education', sa.Enum('GRADUATE', 'UNDER_GRADUATE', name='educationenum'), nullable=False),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('self_employed', sa.Enum('NO', 'YES', name='selfemployeeenum'), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('credit_history', sa.Integer(), nullable=False),
    sa.Column('property_area', sa.Enum('URBAN', 'SEMI_URBAN', 'RURAL', name='propertyareaenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
