"""add loan_term to loan application

Revision ID: fd9aa78d1f7b
Revises: a66cd799f6c2
Create Date: 2024-06-28 10:00:30.966027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd9aa78d1f7b'
down_revision: Union[str, None] = 'a66cd799f6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loanapplication', sa.Column('loan_term', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loanapplication', 'loan_term')
    # ### end Alembic commands ###
